# Generated by Django 5.0.14 on 2025-12-21 23:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("name", models.CharField(max_length=100, verbose_name="اسم الفئة")),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="الاسم بالإنجليزية",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حذف بواسطة",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="inventory.category",
                        verbose_name="الفئة الأب",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة",
                "verbose_name_plural": "الفئات",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("name", models.CharField(max_length=50, verbose_name="اسم الوحدة")),
                ("symbol", models.CharField(max_length=10, verbose_name="الرمز")),
                (
                    "is_base",
                    models.BooleanField(default=True, verbose_name="وحدة أساسية"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حذف بواسطة",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "وحدة قياس",
                "verbose_name_plural": "وحدات القياس",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("name", models.CharField(max_length=255, verbose_name="اسم المنتج")),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الاسم بالإنجليزية",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود المنتج"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="الباركود",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("goods", "بضاعة"),
                            ("service", "خدمة"),
                            ("consumable", "مستهلك"),
                        ],
                        default="goods",
                        max_length=20,
                        verbose_name="نوع المنتج",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="سعر التكلفة",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="سعر البيع",
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="سعر الجملة",
                    ),
                ),
                (
                    "minimum_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="أقل سعر بيع",
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(default=True, verbose_name="خاضع للضريبة"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="نسبة الضريبة",
                    ),
                ),
                (
                    "track_stock",
                    models.BooleanField(default=True, verbose_name="تتبع المخزون"),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الحد الأدنى للمخزون",
                    ),
                ),
                (
                    "maximum_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الحد الأقصى للمخزون",
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="نقطة إعادة الطلب",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="صورة المنتج",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="العلامة التجارية",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="الموديل"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.category",
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حذف بواسطة",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّل بواسطة",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="inventory.unit",
                        verbose_name="وحدة القياس",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج",
                "verbose_name_plural": "المنتجات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("name", models.CharField(max_length=100, verbose_name="اسم المستودع")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز المستودع"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="المستودع الافتراضي"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حذف بواسطة",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدير المستودع",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستودع",
                "verbose_name_plural": "المستودعات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "وارد"),
                            ("out", "صادر"),
                            ("adjustment", "تسوية"),
                            ("transfer", "تحويل"),
                            ("return", "مرتجع"),
                            ("damage", "تالف"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحركة",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("purchase", "مشتريات"),
                            ("sale", "مبيعات"),
                            ("adjustment", "تسوية يدوية"),
                            ("transfer", "تحويل بين مستودعات"),
                            ("opening", "رصيد افتتاحي"),
                            ("return", "مرتجع"),
                        ],
                        max_length=20,
                        verbose_name="مصدر الحركة",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="الكمية"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="تكلفة الوحدة",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="رقم المرجع"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نوع المرجع"
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرف المرجع"
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="الرصيد قبل"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="الرصيد بعد"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بواسطة",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة مخزون",
                "verbose_name_plural": "حركات المخزون",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الكمية المحجوزة",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخزون",
                "verbose_name_plural": "المخزون",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="inventory_p_barcode_3a77e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["code"], name="inventory_p_code_a06c9c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="inventory_p_name_f6a6a1_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "warehouse"], name="inventory_s_product_5d230d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["created_at"], name="inventory_s_created_05ebf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="inventory_s_referen_5aaa1a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("product", "warehouse")},
        ),
    ]
