# Generated by Django 5.0.14 on 2025-12-24 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_convert_existing_product_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_taxable",
            field=models.BooleanField(default=False, verbose_name="خاضع للضريبة"),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="نسبة الضريبة",
            ),
        ),
    ]
