# Generated by Django 5.0.14 on 2025-12-24 11:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_units_management"),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="base_quantity",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=15,
                verbose_name="الكمية بالوحدة الأساسية",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_items",
                to="inventory.productunit",
                verbose_name="وحدة المنتج",
            ),
        ),
    ]
