# Generated by Django 5.0.14 on 2025-12-21 23:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="رمز العملة"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="اسم العملة")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                ("symbol", models.CharField(max_length=10, verbose_name="الرمز")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=15,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="العملة الأساسية"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="عدد الخانات العشرية"
                    ),
                ),
            ],
            options={
                "verbose_name": "عملة",
                "verbose_name_plural": "العملات",
                "ordering": ["-is_primary", "code"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المفتاح"
                    ),
                ),
                ("value", models.TextField(verbose_name="القيمة")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="الوصف"),
                ),
            ],
            options={
                "verbose_name": "إعداد النظام",
                "verbose_name_plural": "إعدادات النظام",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الضريبة")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز الضريبة"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="نسبة الضريبة %",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="الافتراضي"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
            ],
            options={
                "verbose_name": "معدل الضريبة",
                "verbose_name_plural": "معدلات الضريبة",
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
